### ISSUE TITLE
bed output columns missing

### ISSUE THREAD

**Issue by LisaBlazek** [TulsaBioinformaticsToolsmith/LtrDetectorForRepeatModeler#1]
hello!
i have the problem that in the bed output the 8th to 18th column is missing.

for compiling i was only able to use gcc7.3.0 (i work on a cluster without sudo rights),
besides that compiling underwent without problems.

can this two things be linked? 

this was the command i used:
`LtrDetector -fasta .. -destDir . -rawScores -cleanedScores -bedFormat -nThreads 14`

i really like your paper and the program and i hope to use it in future :)
kind regard, 
lisa

**Comment by hani-girgis** [comment]
Hi.

Please remove -bedFormat. The -bedFormat  option prints BED format without additional annotations (PPT and TSD).

Thanks for your interest in our work!

Best regards,

Hani Z. Girgis, PhD

**Comment by LisaBlazek** [comment]
hi hani!

thank you for the fast answer!
i did misunderstood the -bedFormat comand, now everything is working :)

kind regards,
lisa
